### ISSUE TITLE
Fails with perl <= 5.14

### ISSUE THREAD

**Issue by andk** [pplu/cfn-perl#33]
Best illustrated with the matrix: http://matrix.cpantesters.org/?dist=Cfn%200.05

Sample fail report: http://www.cpantesters.org/cpan/report/151e859a-785d-11e9-9066-e374b0ba08e8

Likely cause (untested): package Foo { ... }

Found in: https://metacpan.org/source/JLMARTIN/Cfn-0.05/lib/Cfn.pm#L1

```
package Cfn::TypeLibrary {
```

If you want to keep the `package identifier block` construct, it would be cool if you could predeclare the dependency. That way the FAILS are converted to UNKNOWNS. Details about how to do it are on this page: http://wiki.cpantesters.org/wiki/CPANAuthorNotes

Thanks!

**Comment by pplu** [comment]
Are you going to be using the module for a project? Are you interested in pre-5.14 support?

**Comment by andk** [comment]
>>>>> On Tue, 21 May 2019 03:40:29 -0700, Jose Luis Martinez <notifications@github.com> said:

  > Are you going to be using the module for a project? Are you interested
  > in pre-5.14 support?

I'm not a user. I just analyse fails and help others to keep track of
fails on CPAN. My suggestion was not a request to change any of your
code. The idea is just to declare known limitations of every package.
This helps other statistics to tell intentional fails from unintentional
fails. See for example on this page
http://matrix.cpantesters.org/?dist=Cfn+0.05 how many fails are related
to 'fails on perl < 5.14' and how many have a different reason. If you
declare your intentional fails, it's easier to find the reasons for the
other failures.

Thanks for your interest,
-- 
andreas

**Comment by pplu** [comment]
Just merged https://github.com/pplu/cfn-perl/commit/f84fd857992a000c8af6e72e6b05c4ecde5680d9. Thanks for the suggestion!

**Comment by pplu** [comment]
Just released 0.06 to CPAN with this change. Thanks
