### ISSUE TITLE
Become contributor

### ISSUE THREAD

**Issue by torrentalle** [pplu/cfn-perl#64]
Hello @pplu 

I missed your invitation to become a collaborator of this project. Can you resend it?

Thanks.

**Comment by pplu** [comment]
You are now a contributor to the project. If you give me a PAUSE Id (you can ask for one here: https://pause.cpan.org/pause/query?ACTION=request_id): I'll give you upload permission to CPAN

**Comment by torrentalle** [comment]
thanks a lot. My  PAUSE id is amoreno

**Comment by pplu** [comment]
You are now a PAUSE comaint of the Cfn package
